// Justification cards for the 34 v0.2 actions: definition, anchor, calculation, proof, open questions.
// Numbers are not repeated here; they come from tables-v02.ts wherever a card is rendered (the /methodology
// pages and docs/methodology/cards/*.md via scripts/render-cards.ts), so text and code cannot drift apart.
export interface CardText {
  title: string;
  definition: string; // what one unit is, and which standard defines it
  represents: string; // what the weight stands for
  anchor: string; // physical anchor or "none"
  calc: string; // how the score is computed
  evidence: string; // what proof fits P1–P4
  questions: string[];
  rubric?: [number, number, number]; // Five Dimensions: depth, duration, vulnerability (1–3)
}

export const CARDS_V02: Record<string, CardText> = {
  trees_planted: {
    title: "Trees planted (terrestrial)",
    definition: "Area planted with trees, in hectares, credited per monitored year (ha·yr). A tree count is converted to area with the declared planted area or planting density. Area-based approach as in Verra VM0047 (reference only).",
    represents: "Above-ground carbon uptake of a young tropical plantation per hectare per year.",
    anchor: "IPCC 2019 Refinement Vol. 4 Ch. 4 Table 4.10: Asia, tropical rainforest, \"other\" species, 5 t dry matter/ha/yr; carbon fraction 0.47 (IPCC 2006 GL Table 4.3); 44/12 C→CO2.",
    calc: "5 × 0.47 × 44/12 = 8.62 → 8.6 tCO2e/ha/yr. Score = ha × years × 8.6 × SM × ESM. Count without area or density = 0 carbon and a `needs_area` flag.",
    evidence: "P1 post with photos of the planting; P2 geotagged photos, planting plan with area; P3 landowner or local authority letter; P4 survey or satellite measurement of the planted area.",
    questions: ["Region-specific rates for other zones (Table 4.10 has dry and montane zones).", "Should a tree count without area get a small non-carbon weight?", "How to treat the first years, when young trees capture far less than the average rate?"],
  },
  mangroves_planted: {
    title: "Mangroves planted",
    definition: "Mangrove area planted, in hectares per monitored year (ha·yr), from declared area or density. Current Verra route for mangroves is VM0033 (reference only).",
    represents: "Above-ground carbon uptake of planted tropical mangroves, discounted for survival.",
    anchor: "Bernal, Murray, Pearson 2018, Carbon Balance and Management, Table 2: 23.1 tCO2/ha/yr (±2.9) for years 0–20, tree form; 6.7 for shrub form. Cross-check [derived] IPCC 2013 Wetlands Supplement Tables 4.4 × 4.2 × 44/12 = 16.4 above-ground, ≈24.4 with roots (Table 4.5).",
    calc: "ha × years × 23.1 (6.7 for shrub form) × S × SM × ESM. S = measured surviving share when given, else 0.72 (proxy from Bourgeois et al. 2024: planted stands reach 71–73% of intact biomass after ~20 years).",
    evidence: "P1 public post; P2 geotagged photos and planting records; P3 local authority or partner confirmation; P4 survival survey, drone or satellite area measurement.",
    questions: ["Include soil carbon (+5.9 tCO2e/ha/yr [derived] IPCC 2013 Table 4.12)?", "Is the Bourgeois ratio a fair default survival factor, or should unmonitored planting get a lower default?", "How to credit the first years after planting?"],
  },
  coral_planted: {
    title: "Coral fragments planted",
    definition: "Coral fragments (nubbins) out-planted on a reef. Monitoring metrics follow the NOAA / Coral Restoration Consortium monitoring guide 2020.",
    represents: "Reef habitat restoration per surviving fragment. No carbon or monetary value source exists.",
    anchor: "Weight: none (v0.1 value 0.4 kept). Survival: Boström-Einarsson et al. 2020, PLoS ONE, 60–70% survival across restoration projects; midpoint 0.65.",
    calc: "fragments × 0.4 × S 0.65 × ESM. Measured survival replaces 0.65.",
    evidence: "P2 dated underwater photos of the nursery and out-plant site; P3 dive centre or marine park confirmation; P4 survival monitoring data.",
    questions: ["Value per surviving fragment relative to a hectare of mangroves.", "Score area of restored reef (m²) instead of fragments?"],
    rubric: [2, 2, 2],
  },
  waste_collected_kg: {
    title: "Waste collected",
    definition: "Mass of waste removed from the environment, in kg. Unit definitions: Verra Plastic Standard Waste Collection Credit (1 t plastic), OBP (1 kg ocean-bound plastic), BVRio CCM v2.0 (1 t any solid waste). Evidence schema: Ocean Conservancy ICC data card, NOAA MDMAP.",
    represents: "Pollution removed from beaches, rivers and streets per kg. No public source values litter removal against carbon.",
    anchor: "None (v0.1 value 0.05 per kg kept). Implies 1 t of litter = 50 tCO2e-equivalent points, likely high relative to carbon.",
    calc: "kg × 0.05 × ESM. Tonnes, grams and pounds are converted to kg first; \"bags\" cannot be converted and are flagged.",
    evidence: "P1 public post; P2 geotagged photos of bags and scale, two independent posts; P3 local authority or beach manager confirmation; P4 weighbridge or collection-point receipt.",
    questions: ["Value of 1 kg of litter removed relative to 1 tCO2e.", "Different values for plastic and other waste?", "Beaches refill: should repeated cleanups of the same site count fully?"],
    rubric: [1, 1, 2],
  },
  plastic_recycled_kg: {
    title: "Plastic recycled",
    definition: "Mass of plastic delivered to recycling, in kg. Unit definitions: Verra Waste Recycling Credit, PCX PPRS (1 t).",
    represents: "Carbon avoided by recycling instead of landfilling; when no collection row exists, also the pollution part of collected waste.",
    anchor: "US EPA WARM v16 (Dec 2023) Exhibit 5-3, mixed plastics: recycling −0.93, landfilling +0.02 MTCO2E per short ton → [derived] 1.05 tCO2e per metric t = 0.00105 per kg. US factors.",
    calc: "kg × 0.00105 × ESM. If the report has no `waste_collected_kg` row, 0.05 per kg (pollution part) is added, because the plastic was also collected.",
    evidence: "P2 photos of delivery; P4 receipt from the recycler or collection point.",
    questions: ["Asian recycling factors instead of US WARM factors.", "Pollution value of plastic diverted from open burning."],
  },
  co2_offset_ton: {
    title: "tCO2e with registry serial",
    definition: "Tonnes of CO2e issued or retired in a recognised registry (Verra, Gold Standard, Plan Vivo), identified by serial number.",
    represents: "The anchor of the environment scale: 1 point = 1 tCO2e.",
    anchor: "Definition. Counts only with a registry serial; otherwise 0 and a `registry_required` flag, to prevent double claiming.",
    calc: "tCO2e × 1.0 × ESM. With a serial, tree and area rows of the same report become evidence only (score 0).",
    evidence: "P4 registry record with serial number and retirement.",
    questions: ["Should registry-certified carbon be listed at all in the community layer, or only in the corporate layer?"],
  },
  hectares_restored: {
    title: "Hectares restored",
    definition: "Area of degraded land or coast restored, in hectares per monitored year (ha·yr).",
    represents: "Carbon uptake of restored vegetation per hectare per year. Mangrove sites use the mangrove rate.",
    anchor: "Terrestrial: 8.6 tCO2e/ha/yr [derived] IPCC 2019 Table 4.10 (as trees_planted). Mangrove site (ecosystem = mangrove, or a mangrove row in the report): 23.1 (Bernal 2018) with the mangrove survival factor.",
    calc: "ha × years × rate × SM × ESM (× S for mangrove sites). When the report also counts trees or mangroves, the area row wins and the tree row scores 0.",
    evidence: "P2 geotagged photos, site map; P3 landowner or authority letter; P4 area survey or satellite image.",
    questions: ["Rates for grassland, peat and seagrass restoration.", "Minimum monitoring before multi-year credit."],
  },
  water_purified_liters: {
    title: "Water purified",
    definition: "Litres of safe drinking water supplied, converted to person-days of drinking water. Service definition: WHO/UNICEF JMP \"safely managed\" (SDG 6.1.1).",
    represents: "Days of safe drinking water for one person.",
    anchor: "Gold Standard Safe Drinking Water Supply v2.0 (July 2026): caps of 1.3 L/day under 5, 4.5 L/day ages 5–18, 5.5 L/day adults; 5% deduction when defaults are used. Quality: no detectable E. coli per 100 ml (v1.0). Weight 0.0055 per person-day keeps the v0.1 scale.",
    calc: "person-days = litres ÷ 5.5 × 0.95; score = person-days × 0.0055 × ESM.",
    evidence: "P2 photos of the system in use; P3 school or community confirmation; P4 water quality test (E. coli).",
    questions: ["Value per person-day relative to other actions.", "Full weight only with a water quality test?"],
    rubric: [2, 1, 3],
  },
  renewable_energy_kwh: {
    title: "Renewable energy generated",
    definition: "kWh of solar or wind electricity generated, converted to tCO2e avoided with the country grid factor.",
    represents: "Grid emissions avoided.",
    anchor: "IFI Default Grid Factors v3.0 (Dec 2021, UNFCCC), combined margin for intermittent sources, tCO2e/kWh: TH 0.000413, VN 0.000493, ID 0.000714, PH 0.000617, MY 0.000508, KH 0.000874, LA 0.000876, IN 0.000842. Unknown country: lowest listed factor, flagged.",
    calc: "kWh × grid factor × 1.0 × ESM.",
    evidence: "P2 photos of the installation and meter; P4 inverter or meter export.",
    questions: ["Switch Thailand to the TGO 2026 factor once the official page is reachable.", "Off-grid systems replacing diesel need a different baseline."],
  },
  animals_rescued: {
    title: "Animals rescued",
    definition: "Animals taken into care, by intake type (stray, surrender, confiscation). ICAM Coalition indicators.",
    represents: "Welfare gain for one animal removed from harm. No published source sets relative weights between animal actions.",
    anchor: "None (v0.1 value 0.5).",
    calc: "animals × 0.5.",
    evidence: "P1 public post; P2 intake photos with dates; P3 vet or shelter partner record; P4 official intake register.",
    questions: ["Relative value of rescue, sterilisation, treatment and adoption.", "Wildlife rescue vs companion animals."],
    rubric: [2, 2, 3],
  },
  animals_sterilized: {
    title: "Animals sterilised",
    definition: "Animals neutered or spayed. WOAH Terrestrial Code Ch. 7.7 (7.7.18 reproductive control, 7.7.19 catch-neuter-vaccinate-return).",
    represents: "Population management and welfare over the animal's lifetime.",
    anchor: "None (v0.1 value 0.3). WOAH 7.7 is the strongest citation for definitions, not for value.",
    calc: "animals × 0.3.",
    evidence: "P2 photos with dates; P3 vet clinic record; P4 municipal CNVR register.",
    questions: ["Should sterilisation outrank treatment, given lifetime effect on population?"],
    rubric: [2, 3, 2],
  },
  animals_treated: {
    title: "Animals treated",
    definition: "Animals given veterinary treatment or vaccination. ICAM impact area 1 (welfare).",
    represents: "Short-term welfare gain for one animal.",
    anchor: "None (v0.1 value 0.2). WHO: mass dog vaccination is the main intervention against dog-mediated rabies (TRS 1012, 70% coverage).",
    calc: "animals × 0.2.",
    evidence: "P2 photos; P3 vet record; P4 vaccination register.",
    questions: ["Separate weight for rabies vaccination (public health effect)?"],
    rubric: [2, 1, 3],
  },
  animals_adopted: {
    title: "Animals adopted",
    definition: "Animals placed in a new home (outcome record). Shelter quality check: Asilomar live release rate.",
    represents: "Lasting welfare outcome for one animal.",
    anchor: "None (v0.1 value 0.6). WOAH 7.7.20 covers rehoming.",
    calc: "animals × 0.6.",
    evidence: "P2 photos with adopters; P3 adoption contract; P4 shelter register.",
    questions: ["Follow-up check after adoption before full credit?"],
    rubric: [3, 3, 3],
  },
  wildlife_released: {
    title: "Wildlife released",
    definition: "Wild animals returned to the wild after care. Gate: IUCN/SSC Reintroduction Guidelines 2013 (justification and post-release monitoring).",
    represents: "Return of a wild animal to its population.",
    anchor: "None (v0.1 value 0.8). Always flagged `gate_iucn` for the validator.",
    calc: "animals × 0.8, only after the validator accepts the IUCN gate.",
    evidence: "P2 release photos; P3 wildlife authority permit; P4 tracking data.",
    questions: ["Weight by conservation status of the species (IUCN Red List cannot be queried commercially)."],
    rubric: [3, 3, 3],
  },
  students_taught: {
    title: "Students taught",
    definition: "Students enrolled in and attending a programme. IRIS+ PI2389 School Enrollment.",
    represents: "Learning for one student over the reported programme.",
    anchor: "None (v0.1 value 0.2). Calibration source for the expert round: World Bank LAYS (learning-adjusted years of schooling).",
    calc: "students × 0.2. Workshops in the same report score 0.",
    evidence: "P1 post; P2 class photos with dates; P3 school or partner letter; P4 attendance register or test results.",
    questions: ["Weight by programme length (hours) instead of headcount?", "LAYS per $100 as the calibration route."],
    rubric: [2, 2, 2],
  },
  workshops_held: {
    title: "Workshops held",
    definition: "Number of sessions. No IRIS+ metric; it is an output, not an outcome.",
    represents: "Only used when participants are not counted.",
    anchor: "None (v0.1 value 0.05). Scores 0 when the report counts students, people or teachers trained.",
    calc: "workshops × 0.05, or 0 with participants.",
    evidence: "P2 photos; P3 host confirmation.",
    questions: ["Drop the action and require participant counts?"],
    rubric: [1, 1, 2],
  },
  scholarships_granted: {
    title: "Scholarships granted",
    definition: "Full or partial scholarships. IRIS+ PI4509 Full Scholarship, PI3499 Partial Scholarship.",
    represents: "A year of schooling made possible for one student.",
    anchor: "None (v0.1 value 1.0).",
    calc: "scholarships × 1.0.",
    evidence: "P3 school confirmation; P4 payment record to the school.",
    questions: ["Scale by scholarship amount or duration?"],
    rubric: [3, 3, 3],
  },
  teachers_trained: {
    title: "Teachers trained",
    definition: "Teachers completing training. IRIS+ PI2998 Individuals Trained, PI1902 Teachers Qualified.",
    represents: "Improved teaching reaching future students.",
    anchor: "None (v0.1 value 0.5). GEEAP Smart Buys 2023 rates structured pedagogy with teacher guides as a good buy.",
    calc: "teachers × 0.5.",
    evidence: "P2 training photos; P3 school or education office letter; P4 certificate list.",
    questions: ["Multiply by students reached per teacher?"],
    rubric: [2, 3, 2],
  },
  books_distributed: {
    title: "Books distributed",
    definition: "Books handed out. IRIS+ PI5736 measures instructional materials by currency value, not count (unit mismatch).",
    represents: "Access to reading material.",
    anchor: "None (v0.1 value 0.02). GEEAP: materials alone have weak evidence.",
    calc: "books × 0.02.",
    evidence: "P2 photos; P3 school confirmation.",
    questions: ["Switch to value in USD to match PI5736?"],
    rubric: [1, 2, 2],
  },
  schools_built: {
    title: "Classroom space built",
    definition: "New or improved classroom space in m². IRIS+ PI7268 Classroom Space. A bare count of schools is flagged `needs_area`.",
    represents: "Physical learning space.",
    anchor: "None. 0.1 per m² = v0.1 value of 50 per school ÷ an assumed 500 m². GEEAP: construction alone is not ranked as a good buy.",
    calc: "m² × 0.1.",
    evidence: "P2 photos before and after; P3 education office letter; P4 building permit or handover record.",
    questions: ["Typical classroom area for the region.", "Should construction need complementary inputs (teachers, materials) to score?"],
    rubric: [2, 3, 2],
  },
  meals_provided: {
    title: "Meals provided",
    definition: "Meals served. IRIS+ PI6971 covers school meals only. WFP reference: 2,100 kcal per person per day; no per-meal standard exists.",
    represents: "Short-term food security.",
    anchor: "None (v0.1 value 0.02). With families_supported in the same report, only the higher row counts.",
    calc: "meals × 0.02.",
    evidence: "P1 post; P2 photos with dates; P3 partner or community confirmation; P4 distribution register.",
    questions: ["Define a meal (for example 700 kcal) or switch to person-days of food?"],
    rubric: [1, 1, 3],
  },
  people_housed: {
    title: "People housed",
    definition: "People given housing. IRIS+ PI2491 Housing Units Constructed, PI5965 Housing Units Financed (units, not people).",
    represents: "Shelter for one person.",
    anchor: "None (v0.1 value 1.0).",
    calc: "people × 1.0.",
    evidence: "P2 photos; P3 local authority letter; P4 tenancy or handover record.",
    questions: ["Temporary shelter vs permanent housing.", "Count units instead of people to match IRIS+?"],
    rubric: [3, 3, 3],
  },
  microloans_issued: {
    title: "Microloans issued",
    definition: "Loans disbursed. IRIS+ PI8381 Number of Loans Disbursed.",
    represents: "Access to credit for one borrower.",
    anchor: "None (v0.1 value 0.5).",
    calc: "loans × 0.5.",
    evidence: "P3 partner confirmation; P4 loan register.",
    questions: ["Credit repayment and outcome data before full weight?"],
    rubric: [2, 2, 2],
  },
  jobs_created: {
    title: "Jobs created",
    definition: "Full-time equivalent jobs. IRIS+ PI3687 Jobs Created (FTE), PI9465 Job Placements.",
    represents: "One year of employment.",
    anchor: "None (v0.1 value 1.5). Headcount must be converted to FTE.",
    calc: "FTE × 1.5.",
    evidence: "P3 employer letter; P4 payroll record.",
    questions: ["Adjust by wage relative to World Bank poverty lines ($3.00 / $4.20 / $8.30 per day)?"],
    rubric: [3, 3, 2],
  },
  families_supported: {
    title: "Families supported",
    definition: "Households receiving products or services. IRIS+ PI7954 Client Households, PI1583 Receiving Free Products/Services.",
    represents: "Support for one household.",
    anchor: "None (v0.1 value 0.4). With meals_provided for the same families, only the higher row counts.",
    calc: "families × 0.4.",
    evidence: "P2 photos; P3 community leader confirmation; P4 distribution register.",
    questions: ["What support counts (food, cash, goods)?"],
    rubric: [2, 1, 3],
  },
  clean_water_access_people: {
    title: "People with new clean water access",
    definition: "People provided new access to safe water. IRIS+ PI2822; JMP \"safely managed\" (SDG 6.1.1).",
    represents: "Lasting access to safe water for one person.",
    anchor: "None (v0.1 value 0.3).",
    calc: "people × 0.3.",
    evidence: "P2 photos of the installation; P3 community confirmation; P4 water quality test.",
    questions: ["Should this outrank litres purified, since access lasts?"],
    rubric: [3, 3, 3],
  },
  people_trained: {
    title: "People trained",
    definition: "Individuals completing training. IRIS+ PI2998 Individuals Trained.",
    represents: "Skills gained by one person.",
    anchor: "None (v0.1 value 0.1).",
    calc: "people × 0.1. Workshops in the same report score 0.",
    evidence: "P2 photos; P3 partner letter; P4 attendance list.",
    questions: ["Weight by training hours?"],
    rubric: [2, 2, 2],
  },
  volunteers_mobilized: {
    title: "Volunteers mobilised",
    definition: "Volunteers taking part. IRIS+ OI1166 measures volunteer hours; it is an input, not an outcome.",
    represents: "Nothing in IV. Shown as context next to the outcomes the volunteers produced.",
    anchor: "Weight 0 (sourced: input metric).",
    calc: "0. Flag `input_not_outcome`.",
    evidence: "Counts as supporting evidence for other actions (group photo, sign-up list).",
    questions: ["None."],
  },
  women_empowered: {
    title: "Women empowered",
    definition: "Women reached. IRIS+ PI8330 Client Individuals: Female. Too vague to measure; to be split into training, jobs and loans for women.",
    represents: "Support for one woman.",
    anchor: "None (v0.1 value 0.3).",
    calc: "women × 0.3.",
    evidence: "P2 photos; P3 partner letter; P4 register.",
    questions: ["Split into specific actions and retire this one?"],
    rubric: [2, 2, 3],
  },
  community_events_held: {
    title: "Community events held",
    definition: "Events held. No IRIS+ metric found.",
    represents: "Community engagement.",
    anchor: "None (v0.1 value 0.1).",
    calc: "events × 0.1.",
    evidence: "P1 post; P2 photos.",
    questions: ["Count participants instead of events?"],
    rubric: [1, 1, 1],
  },
  patients_treated: {
    title: "Patients treated",
    definition: "Patients completing treatment. IRIS+ PI5060 Patients Completing Treatment.",
    represents: "Health gain for one patient.",
    anchor: "None (v0.1 value 0.2). Calibration sources: WHO DALY methods (2024), DCP3 (CC BY 3.0 IGO).",
    calc: "patients × 0.2. With vaccinations or kits in the same report, a `review_overlap` flag goes to the validator.",
    evidence: "P2 photos; P3 clinic or health office letter; P4 patient register.",
    questions: ["DALY-based weights by treatment type."],
    rubric: [2, 2, 3],
  },
  vaccinations_administered: {
    title: "Vaccinations administered",
    definition: "Vaccine doses given. No IRIS+ metric; SDG 3.b.1 as context.",
    represents: "Disease prevention for one person.",
    anchor: "None (v0.1 value 0.05). Likely underweighted: health cost-effectiveness evidence ranks vaccination among the highest-value interventions.",
    calc: "vaccinations × 0.05.",
    evidence: "P3 health office confirmation; P4 vaccination register.",
    questions: ["Raise relative to patients treated?"],
    rubric: [2, 3, 3],
  },
  medical_kits_distributed: {
    title: "Medical kits distributed",
    definition: "Kits handed out. No IRIS+ metric.",
    represents: "Access to basic medical supplies.",
    anchor: "None (v0.1 value 0.1).",
    calc: "kits × 0.1.",
    evidence: "P2 photos; P3 partner confirmation.",
    questions: ["Define kit contents."],
    rubric: [1, 1, 3],
  },
  mental_health_sessions: {
    title: "Mental health sessions",
    definition: "Counselling or therapy sessions. No IRIS+ metric.",
    represents: "Mental health support for one session.",
    anchor: "None (v0.1 value 0.15).",
    calc: "sessions × 0.15.",
    evidence: "P3 practitioner confirmation; P4 session register (anonymised).",
    questions: ["Count people completing a course instead of sessions?"],
    rubric: [2, 2, 2],
  },
};
