// Sensitivity test for the v0.2 weights: change each weight by −50% and +50% and check whether the
// ranking of a fixed set of illustrative reports changes. Unstable weights go to experts first.
//
//   node --experimental-strip-types scripts/sensitivity.ts > ../../docs/methodology/sensitivity.md

import { computeImpactValueV02 } from "../src/score-v02.ts";
import { ACTION_WEIGHTS_V02 } from "../src/tables-v02.ts";
import type { ExtractedActionV02, ImpactContextV02 } from "../src/types-v02.ts";

interface Sample {
  name: string;
  actions: ExtractedActionV02[];
  ctx?: ImpactContextV02;
}

// Illustrative reports shaped like small-group work. Not pilot data.
const SAMPLES: Sample[] = [
  { name: "Beach cleanup, 380 kg", actions: [{ actionType: "waste_collected_kg", quantity: 380, unit: "kg" }] },
  { name: "Island cleanup + recycling", actions: [{ actionType: "waste_collected_kg", quantity: 1200, unit: "kg" }, { actionType: "plastic_recycled_kg", quantity: 400, unit: "kg" }] },
  { name: "Mangroves 1.2 ha", actions: [{ actionType: "mangroves_planted", quantity: 3000, unit: "trees", areaHa: 1.2 }], ctx: { esm: 1.3 } },
  { name: "Forest 0.4 ha", actions: [{ actionType: "trees_planted", quantity: 600, unit: "trees", areaHa: 0.4 }] },
  { name: "Coral 150 fragments", actions: [{ actionType: "coral_planted", quantity: 150, unit: "fragments" }] },
  { name: "Dog CNVR 40 + treated 60", actions: [{ actionType: "animals_sterilized", quantity: 40, unit: "animals" }, { actionType: "animals_treated", quantity: 60, unit: "animals" }] },
  { name: "Shelter: 15 rescued, 8 adopted", actions: [{ actionType: "animals_rescued", quantity: 15, unit: "animals" }, { actionType: "animals_adopted", quantity: 8, unit: "animals" }] },
  { name: "English class 30 kids", actions: [{ actionType: "students_taught", quantity: 30, unit: "students" }] },
  { name: "Teacher training 12", actions: [{ actionType: "teachers_trained", quantity: 12, unit: "teachers" }, { actionType: "books_distributed", quantity: 200, unit: "books" }] },
  { name: "Food bank 1500 meals", actions: [{ actionType: "meals_provided", quantity: 1500, unit: "meals" }] },
  { name: "Families supported 40", actions: [{ actionType: "families_supported", quantity: 40, unit: "families" }] },
  { name: "First-aid kits 150", actions: [{ actionType: "medical_kits_distributed", quantity: 150, unit: "kits" }] },
  { name: "Women's training 25", actions: [{ actionType: "women_empowered", quantity: 25, unit: "women" }, { actionType: "community_events_held", quantity: 3, unit: "events" }] },
];

function ranking(): string[] {
  return SAMPLES
    .map((s) => ({ name: s.name, iv: computeImpactValueV02(s.actions, s.ctx).impactValue }))
    .sort((a, b) => b.iv - a.iv || a.name.localeCompare(b.name))
    .map((x) => x.name);
}

function moves(base: string[], next: string[]): number {
  return base.reduce((n, name, i) => n + (next[i] === name ? 0 : 1), 0);
}

const used = new Set(SAMPLES.flatMap((s) => s.actions.map((a) => a.actionType)));
const base = ranking();
const baseIv = new Map(SAMPLES.map((s) => [s.name, computeImpactValueV02(s.actions, s.ctx).impactValue]));

const rows: string[] = [];
for (const [key, w] of Object.entries(ACTION_WEIGHTS_V02)) {
  if (!used.has(key) || w.aw.value === 0 || w.parked) continue;
  const original = w.aw.value;
  const out: number[] = [];
  for (const f of [0.5, 1.5]) {
    w.aw.value = original * f;
    out.push(moves(base, ranking()));
  }
  w.aw.value = original;
  const verdict = out[0] === 0 && out[1] === 0 ? "stable" : out[0] + out[1] <= 2 ? "sensitive" : "unstable";
  rows.push(`| ${key} | ${original} | ${w.aw.status} | ${out[0]} | ${out[1]} | ${verdict} |`);
}

console.log(`# Sensitivity of v0.2 weights (±50%)

_Generated by \`packages/impact-engine/scripts/sensitivity.ts\`. Samples are illustrative reports, not pilot data.
"Moved" = how many of the ${SAMPLES.length} reports change position in the ranking when one weight changes._

## Base ranking

| # | Report | IV v0.2 |
|---|---|---|
${base.map((n, i) => `| ${i + 1} | ${n} | ${baseIv.get(n)} |`).join("\n")}

## Per weight

| Action | Weight | Status | Moved at −50% | Moved at +50% | Verdict |
|---|---|---|---|---|---|
${rows.join("\n")}

Stable: ranking unchanged both ways. Sensitive: 1–2 positions move. Unstable: more; these go to experts first.
Weights that change places across domains depend on the domain coefficients k (all 1.0 until the cost survey).`);
